// <auto-generated />
namespace GrowLog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Fourt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fourt));
        
        string IMigrationMetadata.Id
        {
            get { return "202202101759202_Fourt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
